; vim: set ft=nasm:

extern _smol_origin
extern _smol_total_size
extern _smol_text_start
extern _smol_text_off
extern _smol_text_end
extern _smol_text_size
extern _smol_textandheader_size
extern _smol_data_start
extern _smol_data_off
extern _smol_data_end
extern _smol_data_size
extern _smol_total_filesize
extern _smol_bss_start
extern _smol_bss_off
extern _smol_bss_end
extern _smol_bss_size
extern _smol_dataandbss_size
extern _smol_total_memsize

